{% set name = "python-dwca-reader" %}
{% set version = "0.16.2" %}
{% set hash_val = "2d8bd49401cd7e03d26fbfa72793e0fddf63b7257332351549fa22d6839a7020" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - dwca
    - dwca.darwincore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BelgianBiodiversityPlatform/python-dwca-reader
  doc_url: https://python-dwca-reader.readthedocs.io
  dev_url: https://github.com/BelgianBiodiversityPlatform/python-dwca-reader
  summary: A simple Python package to read Darwin Core Archive (DwC-A) files.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jwcook
